In [1]:
! nvidia-smi

Thu Oct 30 08:57:18 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 577.03                 Driver Version: 577.03         CUDA Version: 12.9     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 1650      WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   49C    P8              1W /   50W |      19MiB /   4096MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [2]:
# First, let's verify which PyTorch version is actually being used
import torch
print(f"PyTorch version: {torch.__version__}")

# Check if CUDA is available without trying to access a device yet
print(f"CUDA available: {torch.cuda.is_available()}")

# If the above shows CUDA is not available, you need to reinstall PyTorch with CUDA support
# Here's code to help diagnose the issue:
import sys
print(f"Python version: {sys.version}")
print(f"Python executable: {sys.executable}")

# Only try to access CUDA device info if CUDA is available
if torch.cuda.is_available():
    print(f"CUDA device count: {torch.cuda.device_count()}")
    print(f"CUDA device name: {torch.cuda.get_device_name(0)}")
else:
    print("CUDA is not available. You need to reinstall PyTorch with CUDA support.")
    print("Run this in your terminal or command prompt:")
    print("pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118")

PyTorch version: 2.7.1+cu118
CUDA available: True
Python version: 3.13.5 | packaged by Anaconda, Inc. | (main, Jun 12 2025, 16:37:03) [MSC v.1929 64 bit (AMD64)]
Python executable: C:\ProgramData\anaconda3\python.exe
CUDA device count: 1
CUDA device name: NVIDIA GeForce GTX 1650


In [3]:
import torch
print(torch.__version__)  # Should show something like 2.x.x+cu118
print(torch.cuda.is_available())  # Should print True
print(torch.cuda.get_device_name(0))   # should print "NVIDIA GeForce GTX 1650"


2.7.1+cu118
True
NVIDIA GeForce GTX 1650


In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns 
import torch

In [5]:
scaler = torch.tensor(7)
scaler

tensor(7)

In [6]:
# acsess the data in int form
scaler.item()


7

In [7]:
scaler.ndim

0

In [8]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [10]:
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
MATRIX[0]

tensor([7, 8])

In [14]:
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6]],
                       [[5,6,7],
                        [8,9,0]],
                       [[2,3,4],
                        [5,6,7]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[5, 6, 7],
         [8, 9, 0]],

        [[2, 3, 4],
         [5, 6, 7]]])

In [15]:
TENSOR.shape

torch.Size([3, 2, 3])

In [16]:
TENSOR.ndim

3

In [17]:
TENSOR[2,1]

tensor([5, 6, 7])

### Random Tensor
#### documentation = https://docs.pytorch.org/docs/stable/generated/torch.rand.html

In [18]:
random_tensor = torch.rand(2,3,2,2,5)
random_tensor

tensor([[[[[0.9730, 0.4464, 0.2164, 0.9131, 0.8478],
           [0.3966, 0.7532, 0.9791, 0.9611, 0.5840]],

          [[0.4569, 0.8049, 0.8852, 0.0292, 0.8174],
           [0.1396, 0.4074, 0.8237, 0.5435, 0.5698]]],


         [[[0.8751, 0.3330, 0.0680, 0.0790, 0.9437],
           [0.8278, 0.8864, 0.2927, 0.2783, 0.7741]],

          [[0.5297, 0.7738, 0.7123, 0.3835, 0.4947],
           [0.5266, 0.5426, 0.9808, 0.0826, 0.4225]]],


         [[[0.9845, 0.3452, 0.7852, 0.5416, 0.5333],
           [0.7020, 0.8478, 0.3766, 0.2752, 0.4601]],

          [[0.0340, 0.4926, 0.7597, 0.9076, 0.1778],
           [0.5287, 0.7828, 0.1100, 0.4964, 0.9329]]]],



        [[[[0.7431, 0.9032, 0.2471, 0.2760, 0.2151],
           [0.2262, 0.0497, 0.3127, 0.1507, 0.1163]],

          [[0.5085, 0.0199, 0.0150, 0.8965, 0.0221],
           [0.9556, 0.7480, 0.3330, 0.9267, 0.8024]]],


         [[[0.3963, 0.9407, 0.6972, 0.2573, 0.6287],
           [0.9490, 0.1667, 0.7776, 0.1739, 0.6770]],

          [[0.9228

In [19]:
random_tensor.ndim

5

In [20]:
# tensor of all zreo 
zeros = torch.zeros(2,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [21]:
#tensor of all ones
ones = torch.ones(2,3)
ones

tensor([[1., 1., 1.],
        [1., 1., 1.]])

### creation of range of tensor and tensor-like
documentation = https://docs.pytorch.org/docs/stable/generated/torch.arange.html

In [22]:
range_ = torch.arange(start = 0,end = 100000 , step= 1000)
range_

tensor([    0,  1000,  2000,  3000,  4000,  5000,  6000,  7000,  8000,  9000,
        10000, 11000, 12000, 13000, 14000, 15000, 16000, 17000, 18000, 19000,
        20000, 21000, 22000, 23000, 24000, 25000, 26000, 27000, 28000, 29000,
        30000, 31000, 32000, 33000, 34000, 35000, 36000, 37000, 38000, 39000,
        40000, 41000, 42000, 43000, 44000, 45000, 46000, 47000, 48000, 49000,
        50000, 51000, 52000, 53000, 54000, 55000, 56000, 57000, 58000, 59000,
        60000, 61000, 62000, 63000, 64000, 65000, 66000, 67000, 68000, 69000,
        70000, 71000, 72000, 73000, 74000, 75000, 76000, 77000, 78000, 79000,
        80000, 81000, 82000, 83000, 84000, 85000, 86000, 87000, 88000, 89000,
        90000, 91000, 92000, 93000, 94000, 95000, 96000, 97000, 98000, 99000])

In [23]:
zeros_of_range = torch.ones_like(input=range_)
zeros_of_range

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1])

### defalt datatype in tensor flow in float 32

In [24]:
float32_tensor = torch.tensor([2.,3.,4.],
                              dtype = None,
                             device = None,
                             requires_grad=False)
float32_tensor.dtype               

torch.float32

In [25]:
float16_tensor = float32_tensor.type(torch.float16)
float16_tensor.dtype

torch.float16

In [26]:
float32_tensor*float16_tensor

tensor([ 4.,  9., 16.])

### most occuring error 
- data type mismatch
- device mismatch
- shape mismatch

In [27]:
float32_tensor.dtype

torch.float32

In [28]:
float32_tensor.device

device(type='cpu')

In [29]:
float32_tensor.shape

torch.Size([3])

### Manipulating Tensors (tensor operations)

Tensor opertions include:
* Addition
* Subtraction
* Multiplication(element-wise)
* Division
* Matrix multiplication

In [30]:
tensor = torch.tensor([1,2,3])

In [31]:
tensor*10

tensor([10, 20, 30])

In [32]:
tensor+10

tensor([11, 12, 13])

In [33]:
torch.mul(tensor,10)

tensor([10, 20, 30])

In [34]:
torch.add(tensor,10)

tensor([11, 12, 13])

### matrix multiplication

In [35]:
tensor1 = torch.tensor([[1,2,3]])

In [36]:
tensor1.shape

torch.Size([1, 3])

In [37]:
tensor2 = torch.tensor([[1],
                        [2],
                        [3]])

In [38]:
torch.matmul(tensor1,tensor2)

tensor([[14]])

In [39]:
torch.matmul(tensor2,tensor1)

tensor([[1, 2, 3],
        [2, 4, 6],
        [3, 6, 9]])

In [40]:
tensor3 = tensor1.T
tensor3

tensor([[1],
        [2],
        [3]])

### basic operation on the the tensor
##### min,max,mean

In [41]:
a = torch.arange(0.,100.,10.)
a,a.dtype

(tensor([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.]), torch.float32)

In [42]:
torch.min(a),a.min()

(tensor(0.), tensor(0.))

In [43]:
torch.max(a),a.max()

(tensor(90.), tensor(90.))

In [44]:
torch.mean(a),a.mean()

(tensor(45.), tensor(45.))

### find position of min and max

In [45]:
torch.argmin(a),a.argmin()

(tensor(0), tensor(0))

In [46]:
torch.argmax(a),a.argmax()

(tensor(9), tensor(9))

In [47]:
a+1

tensor([ 1., 11., 21., 31., 41., 51., 61., 71., 81., 91.])

### Reshaping, stacking, squeezing and unsqueezing tensors(help in dealing with the issue related to shape)

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory
as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side
(hstack)
* Squeeze - removes all `1' dimensions from a tensor
* Unsqueeze - add a `1' dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [48]:
import torch
x= torch.arange(0,10)
x,x.shape

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([10]))

In [49]:
x_reshaped = x.reshape(10,1)
x_reshaped,x_reshaped.shape

(tensor([[0],
         [1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]),
 torch.Size([10, 1]))

In [50]:
x_reshaped2 = x.reshape(1,10)
x_reshaped2,x_reshaped2.shape

(tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 10]))

In [51]:
x_reshaped3 = x.reshape(2,5)
x_reshaped3,x_reshaped3.shape

(tensor([[0, 1, 2, 3, 4],
         [5, 6, 7, 8, 9]]),
 torch.Size([2, 5]))

In [52]:
z = x.view(1,10)
z,z.shape

(tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 10]))

In [53]:
# changes in z will also come in x
z[:,0]=5
z,x

(tensor([[5, 1, 2, 3, 4, 5, 6, 7, 8, 9]]),
 tensor([5, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [54]:
x_stacked = torch.stack([x,x,x,x],dim=1)
x_stacked

tensor([[5, 5, 5, 5],
        [1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6],
        [7, 7, 7, 7],
        [8, 8, 8, 8],
        [9, 9, 9, 9]])

In [55]:
x_stacked = torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[5, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [56]:
x_stacked = torch.vstack([x,x,x,x])
x_stacked

tensor([[5, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [57]:
x_stacked = torch.hstack([x,x,x,x])
x_stacked

tensor([5, 1, 2, 3, 4, 5, 6, 7, 8, 9, 5, 1, 2, 3, 4, 5, 6, 7, 8, 9, 5, 1, 2, 3,
        4, 5, 6, 7, 8, 9, 5, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
x_squeezed = x_reshaped2.squeeze()
x_squeezed,x_squeezed.shape

(tensor([5, 1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([10]))

In [59]:
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
x_unsqueezed,x_unsqueezed.shape

(tensor([[5, 1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 10]))

In [60]:
# permute 
x_original = torch.rand(size=(224,224,3))#height,width,color_chennel
x_permuted = torch.permute(input=x_original,dims=(2,0,1))#color_chennel,height,width
x_permuted.shape

torch.Size([3, 224, 224])

In [61]:
x_original[0,0,0],x_permuted[0,0,0]

(tensor(0.0398), tensor(0.0398))

### Indexing = selecting data from tensor

In [62]:
import torch

In [63]:
x = torch.arange(1,10).reshape(1,3,3)
x,x.shape


(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [64]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [65]:
x[0,1]

tensor([4, 5, 6])

In [66]:
x[0,1,2]

tensor(6)

In [67]:
x[:,:,2]

tensor([[3, 6, 9]])

In [68]:
array = np.arange(0.,10.)
tensor = torch.from_numpy(array)
array,tensor,tensor.dtype # defalt dtype of numpy is float64

(array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64),
 torch.float64)

In [69]:
array = array + 1
array,tensor # hence no change in the tensor if the is changed 

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

In [70]:
tensor = torch.ones(7)
tensor_to_numpy = tensor.numpy()
tensor_to_numpy

array([1., 1., 1., 1., 1., 1., 1.], dtype=float32)

### random seed : reduce randomness

In [71]:
randomA = torch.rand(3,4)
randomB = torch.rand(3,4)
randomA == randomB,randomA,randomB

(tensor([[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]]),
 tensor([[0.5226, 0.4244, 0.1072, 0.8763],
         [0.4390, 0.7581, 0.1383, 0.0730],
         [0.2580, 0.5037, 0.0279, 0.9076]]),
 tensor([[0.1184, 0.8460, 0.7075, 0.5462],
         [0.6858, 0.4655, 0.6652, 0.1763],
         [0.4054, 0.7363, 0.5029, 0.6936]]))

In [72]:
random_seed = 42 
torch.manual_seed(random_seed)


In [73]:
torch.manual_seed(random_seed)
randomC = torch.rand(3,4)
torch.manual_seed(random_seed)
randomD = torch.rand(3,4)
randomC,randomD,randomC==randomD

(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]))

### putting our tensor on gpu
- we use gpu for faster computation
- defalt device is cpu is comparatively weaker than gpu

In [75]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [76]:
tensor = torch.tensor([1,2,3],device = device)
tensor,tensor.device

(tensor([1, 2, 3], device='cuda:0'), device(type='cuda', index=0))

In [78]:
# anather mathod 
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [83]:
# if tensor is on gpu then we will not be able to convert to numpy
tensor_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_on_cpu,tensor_on_cpu.device

(array([1, 2, 3]), 'cpu')